import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu";
import { Provider } from "@/context/store";
import Menubtn from "@/components/menubtn";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Menu></Menu>
          {children}
          <Menubtn></Menubtn>
        </Provider>
      </body>
    </html>
  );
}
